# fly.toml app configuration file generated for neoteq-ipn-dns on 2025-02-18T11:55:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neoteq-ipn-dns'
primary_region = 'ams'

[[mounts]]
  source = "ipn_dns_root"
  destination = "/root"

[[services]]
  protocol = "udp"
  internal_port = 53

  [[services.ports]]
    port = 53
